export default {
  FETCH_CONTENT: "FETCH_CONTENT",
  FETCH_CONTENT_SUCCESS: "FETCH_CONTENT_SUCCESS",
  FETCH_CONTENT_ERROR: "FETCH_CONTENT_ERROR",

  FETCH_ARTICLE: "FETCH_ARTICLE",
  FETCH_ARTICLE_SUCCESS: "FETCH_ARTICLE_SUCCESS",
  FETCH_ARTICLE_ERROR: "FETCH_ARTICLE_ERROR"
};
